#!/usr/bin/env python3
import click

# -----------------------------------------------------------------------------
# Group setup
# -----------------------------------------------------------------------------


@click.group(help='shiftuser development commands')
def cli():
    pass


# -----------------------------------------------------------------------------
# Commands
# -----------------------------------------------------------------------------

@cli.command(name='importable')
def importable():
    """ Make shiftuser module importable"""
    import site
    import os

    pth = 'shiftuser.pth'
    dst = os.path.join(site.getsitepackages()[0], pth)
    if os.path.exists(dst):
        print('Destination path file exists! {}\n'.format(dst))
        return

    import_from_here = os.path.dirname(os.path.realpath(__file__))
    with open(dst, 'a') as file:
        file.write('{}\n'.format(import_from_here))


@cli.command(name='test', context_settings=dict(ignore_unknown_options=True))
@click.argument('nose_argsuments', nargs=-1, type=click.UNPROCESSED)
def test(nose_argsuments):
    """ Run shiftuser tests """
    from nose import run
    params = ['__main__', '-c', 'nose.ini']
    params.extend(nose_argsuments)
    run(argv=params)


@cli.command(name='build')
def build():
    """ Build with setuptools"""
    pass


@cli.command(name='publish')
def publish():
    """ Publish to PyPI with twine"""
    pass

# -----------------------------------------------------------------------------
# And run
# -----------------------------------------------------------------------------


cli()
